[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "BDuS1SDwA4NdZRVdUdDLF1r51kuTpYonHUhrfkgEBcfN"

[registry]
url = "https://api.apr.dev"

[provider]
# Test
cluster = "localnet"
# Deploy
# cluster = "https://devnet.helius-rpc.com/?api-key=caa07251-8fc5-4448-9ea9-818537de7be3"
wallet = "~/.config/solana/id.json"

[scripts]
# Test
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# Deploy
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 script/**/*.ts"